steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', 'gcr.io/$PROJECT_ID/villith/brokerpongbot:$SHORT_SHA .' ]
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [ 'push', 'gcr.io/$PROJECT_ID/villith/brokerpongbot:$SHORT_SHA .' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'brokerpongbot', '--image', 'gcr.io/$PROJECT_ID/villith/brokerpongbot:$SHORT_SHA', '--region', 'us-central1-b', '--platform', 'managed', '--allow-unauthenticated']
images:
  - 'gcr.io/$PROJECT_ID/villith/brokerpongbot:$SHORT_SHA'

timeout: 1200s